### PR TITLE
Inventory, Toolbar, and cursor updates. Bug fixes.

### PR DESCRIPTION
**Pull request by mapedorr**
Improvements for inventory items.
Simplified the scene structure for Inventory (previously InventoryContainer) and Toolbar.
Updated all PowerQuest assets by Popochiu ones.

### CODE REVIEW

**Comment by stickgrinder** [comment]
Just letting you know I'm following your work and can't wait to try Popochiu out in the hope to switch out of Unity and into Godot! :)
Keep it going! <3

**Comment by mapedorr** [comment]
Thank you so much for your comment 🥲. It makes feel very happy to know the project is interesting for others.

This week I'll start working on the documentation, so I hope to have it ready as soon as possible so that others can start using the plugin.

**Comment by stickgrinder** [comment]
It's a while I wanted to get in touch to offer my support. Have you got a Discord server or any other channel to get involved with the project?

**Comment by mapedorr** [comment]
That sounds great! I'll create the Discord server for the project this week. Having support will help the project a lot.

**Comment by stickgrinder** [comment]
Looking forward to it! :+1:

**Comment by mapedorr** [comment]
Hey @stickgrinder . I've created the Discord server already: https://discord.gg/Frv8C9Ters

**Pull request merged**
